** My (pretty small) emacs config
This is my first try at making a fairly-detailed emacs config by hand. I've had
previous experience with spacemacs, but (for me) it was kinda sluggish and I
didn't really understand all the things they were doing under the hood.

I started with this config so I could have a good grip on everything I was
adding to the editor. I also show a preference in here for idiomatic and
declarative configuration, use of helper modules provided by the community (such
as the [[https://github.com/raxod502/straight.el][straight package manager]]), and neatly-kept passages using
~outshine-mode~.

** Some 'features'

 - An inital configuration to make emacs a bit more modern looking and less
   annoying, without bloating it to death
 - Packages installed and configured with [[https://github.com/raxod502/straight.el][straight]] and [[https://github.com/jwiegley/use-package][use-package]]
 - Decent amount of configured packages for everyday things (programming
   helpers, completion with ivy/company, magit)
 - Never forget another key chord with [[https://github.com/justbur/emacs-which-key][which-key]]
 - Some helper functions for getting around quick, one key to open conifg file
   in new frame

** License

The entirety of this repo is available under the MIT license in ~LICENSE.txt~,
feel free to use it as you see fit.
